name: DailyReward
main: shian.daily.Main
version: 1.0.0
description: 測試
permissions:
  dailyreward.*:
    description: Allow
    children:
      dailyreward.command: true
      dailyreward.admin: true
  dailyreward.command:
    description: 每日禮包
    default: true
  dailyreward.admin:
    description: 每日禮包設定
    default: op
commands:
  dailyreward:
    description: 每日禮包
    aliases: [dr,dy]
  dailyadmin:
    description: 禮包設置

